### ISSUE TITLE
Column offset is incorrect on the first line

### ISSUE THREAD

**Issue by LadyCailin** [LadyCailin/MethodScriptVSC#11]
![image](https://user-images.githubusercontent.com/647786/64323187-46361580-cfc4-11e9-9321-242435f8c8c0.png)

Despite the way it seems, this is because the first line is correct, and the second line is off by two, but since we globally correct by 2, it causes everything to be right, except for the line that was already right. Anyways, the solution is to get the code target column data correct, then remove the offset in the LangServ.

**Comment by PseudoKnight** [comment]
This appears to have been fixed in this commit:

https://github.com/EngineHub/CommandHelper/commit/2f7b2dc2b737ecc5728e27b4640c4d0748e9cc73

In any case, I cannot replicate it anymore.
