### ISSUE TITLE
Profile is re-requested each startup

### ISSUE THREAD

**Issue by LadyCailin** [LadyCailin/MethodScriptVSC#15]
There appears to be a bug in how the profile file is stored, and either it isn't being stored correctly, or it isn't be read correctly. Therefore, there is a prompt to load the profile again at each startup.

**Comment by jusobreira** [comment]
following

**Comment by LadyCailin** [comment]
It appears that this might only affect the global profile, so selecting the workspace profile might work as a workaround.
